import fs from 'fs';
import path from 'path';
import { optimize } from 'svgo';
import chalk from 'chalk';
import open from 'open';

const DEFAULT_OPTIONS = {
  inputDirectory: './assets',
  outputFile: './snippets/icon.liquid',
  outputFileJSON: '',
  previewFile: 'icon-preview.html',
  flattenFolders: true,
  verbose: true,
  preview: true,
  openPreview: false,
  svgoConfig: {
    multipass: true,
    plugins: [
      { name: 'preset-default' },
      'removeViewBox'
    ]
  }
};

export default function VitePluginShopifyIcons(userOptions = {}) {
  const options = { ...DEFAULT_OPTIONS, ...userOptions };
  const { inputDirectory, outputFile, flattenFolders, verbose, outputFileJSON, previewFile, preview, openPreview, svgoConfig} = options;

  const cache = new Map();
  let rebuildTimeout;
  let previewOpened = false;

  function log(message, color = 'green') {
    if (verbose) console.log(chalk[color](`[vite-plugin-shopify-icons] ${message}`));
  }

  function getAllSvgFiles(dir) {
    const files = [];
    for (const item of fs.readdirSync(dir)) {
      const fullPath = path.join(dir, item);
      const stats = fs.statSync(fullPath);
      if (stats.isDirectory()) {
        files.push(...getAllSvgFiles(fullPath));
      } else if (item.endsWith('.svg')) {
        files.push(fullPath);
      }
    }
    return files;
  }

  function buildIconSnippet() {
    if (!fs.existsSync(inputDirectory)) {
      log(`Input directory not found: ${inputDirectory}`, 'yellow');
      return;
    }

    const svgFiles = flattenFolders ? getAllSvgFiles(inputDirectory) : fs.readdirSync(inputDirectory).filter(f => f.endsWith('.svg')).map(f => path.join(inputDirectory, f));

    const icons = [];

    for (const inputPath of svgFiles.sort()) {
      const fileName = path.basename(inputPath, '.svg');
      const relativeName = flattenFolders
        ? path.relative(inputDirectory, inputPath).replace(/\.svg$/, '').replace(/[\\/]/g, '-')
        : fileName;

      const stats = fs.statSync(inputPath);
      const mtime = stats.mtimeMs;

      if (cache.get(relativeName) === mtime) continue;
      cache.set(relativeName, mtime);

      const rawFile = fs.readFileSync(inputPath, 'utf8');
      const optimized = optimize(rawFile, { path: inputPath, ...svgoConfig });
      icons.push({ name: relativeName, svg: optimized.data });
    }

    if (icons.length === 0) {
      log('No updated icons found, skipping regeneration.', 'gray');
      return;
    }

    const lines = [];
    lines.push(`{% comment %} Auto-generated by vite-plugin-shopify-icons {% endcomment %}
{% comment %}
  Renders an icon
  Accepts:
    - name: Icon file name (required)
    - class: icon classes
    - fill: Icon color fill
    - width: Icon width
    - height: Icon height
    - label: Icon aria label
    - role: Icon role
    - containerAttributes: Extra attributes for svg container
    - iconAttributes: Extra attributes for svg element
  Usage:
    {% render 'icon', name: 'icon-cart', class: 'icon--md', fill: 'red', label: 'cart button', role: 'button'%}
{% endcomment %}`);

    lines.push(`
{% assign icon_class = "icon icon-" | append: name | replace: 'icon-icon-', 'icon-' %}
{% assign icon_fill = fill | default: "currentColor" %}
{% assign icon_extra_class = class | default: "" %}
{% assign icon_label = label | default: name %}
{% assign icon_role = role | default: "" %}
{% assign icon_width = width | default: "" %}
{% assign icon_height = height | default: "" %}
{% assign icon_container_attributes = containerAttributes | default: "" %}
{% assign icon_attributes = iconAttributes | default: "" %}
{% case name %}
`);

    for (const icon of icons) {
      const svg = icon.svg
        .replace(/<svg([^>]*)>/, `<svg$1 role="{{ icon_role }}" {% if width != blank %}width="{{ icon_width }}"{% endif %} {% if height != blank %}height="{{ icon_height }}"{% endif %} fill="{{ icon_fill }}" aria-label="{{ icon_label }}" {{ icon_attributes }}>`)
        .replace(/\n/g, '')
        .trim();

      lines.push(`  {% when "${icon.name}" %}
  <div class="{{ icon_class }} {{ icon_extra_class }}" style="display:inline;color:{{ icon_fill }}" {{ icon_container_attributes }}>
    ${svg}
  </div>`);
    }

    lines.push('{% endcase %}');

    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, lines.join('\n'), 'utf8');
    log(`Generated snippet with ${icons.length} icons → ${outputFile}`);

    if (outputFileJSON) {
      const list = Array.from(cache.keys()).sort();
      fs.writeFileSync(outputFileJSON, JSON.stringify({ icons: list }, null, 2), 'utf8');
      log(`Generated icon list → ${outputFileJSON}`);
    }

    if (preview) buildIconPreview(icons);
  }

  function buildIconPreview(icons) {
    if (!icons || icons.length === 0) return;

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Shopify Icons Preview</title>
  <style>
    body { font-family: sans-serif; padding: 2rem; background: #f8f9fa; }
    h1 { font-size: 1.5rem; margin-bottom: 1rem; }
    input { padding: 0.5rem 0.75rem; width: 100%; max-width: 400px; margin-bottom: 1.5rem; border: 1px solid #ccc; border-radius: 6px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap: 1.5rem; }
    .icon-card { text-align: center; background: #fff; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); transition: transform 0.1s; }
    .icon-card:hover { transform: scale(1.05); }
    .icon-card svg { width: 32px; height: 32px; fill: currentColor; margin-bottom: 0.5rem; }
    .icon-name { font-size: 0.8rem; color: #444; word-break: break-all; }
  </style>
</head>
<body>
  <h1>Shopify Icons Preview (vite-plugin-shopify-icons-liquid)</h1>
  <input type="text" id="search" placeholder="Search icon..." oninput="filterIcons(this.value)" />
  <div class="grid">
    ${icons.map(icon => `
      <div class="icon-card" data-name="${icon.name}">
        ${icon.svg}
        <div class="icon-name">${icon.name}</div>
      </div>
    `).join('\n')}
  </div>

  <script>
    function filterIcons(q) {
      document.querySelectorAll('.icon-card').forEach(card => {
        card.style.display = card.dataset.name.toLowerCase().includes(q.toLowerCase()) ? '' : 'none';
      });
    }
  </script>
</body>
</html>
`;

    fs.mkdirSync(path.dirname(previewFile), { recursive: true });
    fs.writeFileSync(previewFile, html, 'utf8');
    log(`Generated preview page → ${previewFile}`, 'cyan');
  }

  function previewInBrowser(serverUrl) {
    if (previewOpened) return;
    const previewPath = path.resolve(previewFile);
    const url = `${serverUrl.replace(/\/$/, '')}/${path.relative(process.cwd(), previewPath)}`;
    previewOpened = true;
    log(`Preview available at ${url}`, 'cyan');

    if (openPreview) {
      open(url);
    }
  }

  function debouncedBuild() {
    clearTimeout(rebuildTimeout);
    rebuildTimeout = setTimeout(buildIconSnippet, 250);
  }

  return {
    name: 'vite-plugin-shopify-icons-liquid',
    enforce: 'pre',

    configResolved(config) {
      if (config.command === 'build') buildIconSnippet();
    },

    configureServer(server) {
      if (!fs.existsSync(inputDirectory)) return;
      log(`Watching ${inputDirectory} for SVG changes...`);
      server.watcher.add(inputDirectory);
      server.watcher.on('change', (filePath) => {
        if (filePath.endsWith('.svg')) {
          log(`Detected change in: ${filePath}`, 'cyan');
          debouncedBuild();
        }
      });

      server.httpServer?.once('listening', () => {
        const address = server.httpServer.address();
        const host = typeof address === 'object' && address?.port ? `http://localhost:${address.port}` : 'http://localhost:5173';
        previewInBrowser(host);
      });
    },

    buildStart() {
      buildIconSnippet();
    },
  };
}
